### ISSUE TITLE
error when copying the file cisco-pt.desktop from the usr/share/applications directory

### ISSUE THREAD

**Issue by Bayanist36** [konradmb/PacketTracer-AppImage#14]
Это может быть связано с тем, что вы используете неправильный или устаревший .yml файл для сборки AppImage.
![Снимок экрана от 2024-02-07 23-19-07](https://github.com/konradmb/PacketTracer-AppImage/assets/84194314/478a7e16-8fa2-48a7-8c9f-0d9d1fd81f48)
I am attaching a screenshot and logs.
[logs.txt](https://github.com/konradmb/PacketTracer-AppImage/files/14201165/logs.txt)

**Comment by konradmb** [comment]
Right, sorry, fixing it now.
