### ISSUE TITLE
Hi konradmb! can you update this project to match the latest version of packet tracer (v7.3.0)? 

### ISSUE THREAD

**Issue by h599** [konradmb/PacketTracer-AppImage#3]
i have a hard time installing this app on my machine XD
and many people still facing the same issue, 
Thanks for your hard work :D

**Comment by h599** [comment]
btw im using debian testing

**Comment by konradmb** [comment]
Hi h599!
For now I've reverted to the version that needs you to download archive manually, as the download links from Cisco are dead now.

I see that they're providing a .deb now, so I'll add a new .yml file for 7.3. Maybe it will be easier now, because pkg2appimage has built-in support for deb.

**Comment by konradmb** [comment]
@h599 
Ok, I've updated the master branch. Please check out if it works for you. If you have any issues, just tell. If it works fine, feel free to close this issue.

**Comment by h599** [comment]
thanks alot 👍

Pada tanggal Sab, 9 Mei 2020 06.39, konradmb <notifications@github.com>
menulis:
