### ISSUE TITLE
Upgrade for the last version of Packet Tracer

### ISSUE THREAD

**Issue by franciscomp481** [konradmb/PacketTracer-AppImage#4]
Hello!

Firstly I want to thank you for the amazing job you have done with this AppImage.

I just have one question: is it possible for you to upgrade the version of Packet Tracer? 7.3.0 is a bit old and I can't open some projects.

**Comment by konradmb** [comment]
Sure! I remember I've been trying to do it, but something was stopping me. I'll dust it off and get back to you shortly. (famous last words)

**Comment by franciscomp481** [comment]
Thank you for your reply!

**Comment by konradmb** [comment]
Done! Please test it and if something's wrong - reopen this issue.
