### ISSUE TITLE
dumb question build 810 on ubuntu 18.04

### ISSUE THREAD

**Issue by dikdust** [konradmb/PacketTracer-AppImage#6]
hi sorry but I guess that is an appimage question ...

I'm trying to build 810 on ubuntu 18.04 with your yml

when I launch it I have

`./PacketTracer: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./PacketTracer)
./PacketTracer: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./PacketTracer)
./PacketTracer: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_Packet8HYPjb/usr/lib/x86_64-linux-gnu/libQt5Multimedia.so.5)
./PacketTracer: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_Packet8HYPjb/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5)
./PacketTracer: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_Packet8HYPjb/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5)
./PacketTracer: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.28' not found (required by /tmp/.mount_Packet8HYPjb/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5)
./PacketTracer: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_Packet8HYPjb/usr/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5)
./PacketTracer: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_Packet8HYPjb/usr/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5)
./PacketTracer: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_Packet8HYPjb/usr/lib/x86_64-linux-gnu/libQt5WebEngineCore.so.5)
./PacketTracer: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_Packet8HYPjb/usr/lib/x86_64-linux-gnu/libQt5Quick.so.5)
./PacketTracer: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_Packet8HYPjb/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5)
./PacketTracer: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_Packet8HYPjb/usr/lib/x86_64-linux-gnu/libQt5Qml.so.5)
./PacketTracer: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.28' not found (required by /tmp/.mount_Packet8HYPjb/usr/lib/x86_64-linux-gnu/libQt5Xml.so.5)
./PacketTracer: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_Packet8HYPjb/usr/lib/x86_64-linux-gnu/libQt5Xml.so.5)
./PacketTracer: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_Packet8HYPjb/usr/lib/x86_64-linux-gnu/libQt5Script.so.5)
./PacketTracer: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_Packet8HYPjb/usr/lib/x86_64-linux-gnu/libQt5Positioning.so.5)
./PacketTracer: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_Packet8HYPjb/usr/lib/x86_64-linux-gnu/libQt5Core.so.5)
./PacketTracer: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.28' not found (required by /tmp/.mount_Packet8HYPjb/usr/lib/x86_64-linux-gnu/libQt5Core.so.5)
./PacketTracer: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.mount_Packet8HYPjb/usr/lib/x86_64-linux-gnu/libQt5Core.so.5)
./PacketTracer: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_Packet8HYPjb/usr/lib/x86_64-linux-gnu/libQt5Core.so.5)`

I guess I need 20.04 or there is something I can do ?

Feel free to "point the finger" !

**Comment by konradmb** [comment]
Well, there's nothing we can do, because Cisco compiles it with a certain glibc version (2.29) and since glibc is only backwards-compatible - you can't use newer binary with older version. They have Ubuntu 20.04 LTS as a minimum requirement: https://www.netacad.com/courses/packet-tracer/faq
Normally, you would recompile a program to use older glibc, but you can't do this here obviously.

In the future, I think, I will make a Flatpak version of this, so you would be able to run it virtually anywhere.
