### ISSUE TITLE
Not allows to enter with NetAcad Account

### ISSUE THREAD

**Issue by abelsouzacosta** [konradmb/PacketTracer-AppImage#9]
After build the AppImage it not allows to login into NetAcad, the login page is always blank.

There are any solutions?
![image](https://user-images.githubusercontent.com/30609244/230711120-636d86bd-897a-44b3-a7e8-87edc9ac5c06.png)
![image](https://user-images.githubusercontent.com/30609244/230711141-40badc3e-4230-41df-afe6-4a72f7a42c05.png)

**Comment by konradmb** [comment]
Weird, it works for me.
Can you tell me:

- The version of PacketTracer you're using?
- OS name and version?
- Did you build it yourself or downloaded form somewhere else?

**Comment by konradmb** [comment]
@abelsouzacosta H- hello?

**Comment by abelsouzacosta** [comment]
Sorry for the late of the reply bro, my bad.

I'm using version 8.2.0.0162

When i troubleshooted the problem it seemed that the dependency libxcb-xinerama0 was missing, so i installed it and now its working. Tbh, i don't know why, and i don't know what this dependency does

Anyways, thank you bro

![image](https://user-images.githubusercontent.com/30609244/236881435-f4f090ff-cd03-42cc-aa68-aaf85de4cc4e.png)
